In [36]:
import osmap_utils

In [37]:
import pandas as pd

In [38]:
dataset = pd.read_pickle("./names_aqi_median.pkl")

In [39]:
dataset

,Набережная Тараса Шевченко,1905 года улица,Баррикадная улица,Бережковская набережная,Варшавское шоссе,Волгоградский проспект,Воробьёвская набережная,Госпитальная набережная,Дмитровское шоссе,Звенигородское шоссе,Каширское шоссе
1,94.383034,94.406998,94.417427,122.760002,66.104958,66.111282,122.700195,94.421097,66.128014,66.093376,47.218025
2,94.443848,94.397575,NaN,122.731880,66.079254,66.075890,122.706886,NaN,66.080269,66.088364,47.216122
3,94.421707,94.405357,NaN,122.762596,66.064178,66.081039,122.729248,NaN,66.088181,66.073273,47.222225
4,94.413399,94.398964,NaN,122.751930,66.102448,66.102112,122.700043,NaN,66.081535,66.087975,NaN
5,94.425400,NaN,NaN,122.714508,66.097351,66.094681,122.703148,NaN,66.116295,66.070412,NaN
6,NaN,NaN,NaN,NaN,66.076553,66.082314,122.742714,NaN,66.106659,66.069458,NaN
7,NaN,NaN,NaN,NaN,66.095657,66.087845,NaN,NaN,66.078995,66.101547,NaN
8,NaN,NaN,NaN,NaN,66.098869,66.061531,NaN,NaN,66.087975,66.110214,NaN
9,NaN,NaN,NaN,NaN,66.082947,66.078491,NaN,NaN,66.082672,NaN,NaN
10,NaN,NaN,NaN,NaN,66.103882,66.070351,NaN,NaN,66.068459,NaN,47.193069
11,NaN,NaN,NaN,NaN,66.100891,66.096436,NaN,NaN,66.103470,NaN,47.215580
12,NaN,NaN,NaN,NaN,66.113564,66.076164,NaN,NaN,66.075691,NaN,47.215923
13,NaN,NaN,NaN,NaN,66.063019,66.093483,NaN,NaN,66.115387,NaN,47.192554
14,NaN,NaN,NaN,NaN,66.084396,66.081528,NaN,NaN,66.090385,NaN,47.192364
15,NaN,NaN,NaN,NaN,66.047821,66.065430,NaN,NaN,66.118973,NaN,47.199322
16,NaN,NaN,NaN,NaN,66.087189,66.082298,NaN,NaN,66.074318,NaN,47.188812
17,NaN,NaN,NaN,NaN,66.115295,66.097656,NaN,NaN,66.093582,NaN,47.234043
18,NaN,NaN,NaN,NaN,66.083199,66.083382,NaN,NaN,66.091660,NaN,47.199711
19,NaN,NaN,NaN,NaN,66.134369,66.089005,NaN,NaN,66.110428,NaN,47.191650
20,NaN,NaN,NaN,NaN,66.069176,66.057701,NaN,NaN,66.063065,NaN,47.221874
21,NaN,NaN,NaN,NaN,66.079498,66.079597,NaN,NaN,66.075897,NaN,47.190742
22,NaN,NaN,NaN,NaN,66.086090,66.075256,NaN,NaN,66.082886,NaN,47.174122
23,NaN,NaN,NaN,NaN,66.091011,66.074821,NaN,NaN,66.078865,NaN,47.216106
24,NaN,NaN,NaN,NaN,66.074196,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,66.089821,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,66.081657,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,66.094353,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,66.088486,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,66.075211,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
for c in dataset:
    col = dataset[c]
    print(col.dropna())

1    94.383034
2    94.443848
3    94.421707
4    94.413399
5    94.425400
Name: Набережная Тараса Шевченко, dtype: float64
1    94.406998
2    94.397575
3    94.405357
4    94.398964
Name: 1905 года улица, dtype: float64
1    94.417427
Name: Баррикадная улица, dtype: float64
1    122.760002
2    122.731880
3    122.762596
4    122.751930
5    122.714508
Name: Бережковская набережная, dtype: float64
1     66.104958
2     66.079254
3     66.064178
4     66.102448
5     66.097351
6     66.076553
7     66.095657
8     66.098869
9     66.082947
10    66.103882
11    66.100891
12    66.113564
13    66.063019
14    66.084396
15    66.047821
16    66.087189
17    66.115295
18    66.083199
19    66.134369
20    66.069176
21    66.079498
22    66.086090
23    66.091011
24    66.074196
25    66.089821
26    66.081657
27    66.094353
28    66.088486
29    66.075211
Name: Варшавское шоссе, dtype: float32
1     66.111282
2     66.075890
3     66.081039
4     66.102112
5     66.094681
6     66.082314
7     66.087845
8     66.061531
9     66.078491
10    66.070351
11    66.096436
12    66.076164
13    66.093483
14    66.081528
15    66.065430
16    66.082298
17    66.097656
18    66.083382
19    66.089005
20    66.057701
21    66.079597
22    66.075256
23    66.074821
Name: Волгоградский проспект, dtype: float64
1    122.700195
2    122.706886
3    122.729248
4    122.700043
5    122.703148
6    122.742714
Name: Воробьёвская набережная, dtype: float64
1    94.421097
Name: Госпитальная набережная, dtype: float64
1     66.128014
2     66.080269
3     66.088181
4     66.081535
5     66.116295
6     66.106659
7     66.078995
8     66.087975
9     66.082672
10    66.068459
11    66.103470
12    66.075691
13    66.115387
14    66.090385
15    66.118973
16    66.074318
17    66.093582
18    66.091660
19    66.110428
20    66.063065
21    66.075897
22    66.082886
23    66.078865
Name: Дмитровское шоссе, dtype: float64
1    66.093376
2    66.088364
3    66.073273
4    66.087975
5    66.070412
6    66.069458
7    66.101547
8    66.110214
Name: Звенигородское шоссе, dtype: float64
1     47.218025
2     47.216122
3     47.222225
10    47.193069
11    47.215580
12    47.215923
13    47.192554
14    47.192364
15    47.199322
16    47.188812
17    47.234043
18    47.199711
19    47.191650
20    47.221874
21    47.190742
22    47.174122
23    47.216106
Name: Каширское шоссе, dtype: float64

In [41]:
cord_to_value = {}

In [42]:
finder = osmap_utils.StreetSearcher(city="Москва")

In [43]:
import matplotlib.pyplot as plt

In [44]:
for c in dataset.keys():
    sensors = list(dataset[c].dropna())
    cords = [ct.get_cord() for ct in finder.query_cords(c)]
    
    for si in range(len(sensors)):
        cord_to_value[cords[si % len(cords)]] = sensors[si]

In [45]:
cord_to_value

{(55.7467696, 37.5727272): 94.3830337524414,
 (55.7458937, 37.5725665): 94.44384765625,
 (55.752403, 37.5682922): 94.42170715332031,
 (55.7485269, 37.5723747): 94.41339874267578,
 (55.7435597, 37.5384646): 94.42539978027344,
 (55.7667708, 37.5595099): 94.40699768066406,
 (55.7558591, 37.5590651): 94.39757537841797,
 (55.7592331, 37.5580408): 94.40535736083984,
 (55.7700541, 37.5557198): 94.39896392822266,
 (55.7591488, 37.5838317): 94.41742706298828,
 (55.7442717, 37.5718048): 122.71450805664062,
 (55.7355449, 37.5619465): 122.73188018798828,
 (55.7288191, 37.547184): 122.7625961303711,
 (55.7288233, 37.5466866): 122.7519302368164,
 (55.4088783, 37.4747983): 66.07521057128906,
 (55.4153027, 37.4945676): 66.08165740966797,
 (55.4156571, 37.4959933): 66.09435272216797,
 (55.4078659, 37.5512784): 66.08848571777344,
 (55.7080629, 37.74528): 66.08900451660156,
 (55.705214, 37.7669823): 66.05770111083984,
 (55.7093675, 37.731305): 66.07959747314453,
 (55.7094769, 37.7343882): 66.07525634765625,
 (55.7052166, 37.769578): 66.07482147216797,
 (55.7024758, 37.7908443): 66.0654296875,
 (55.7039351, 37.7796415): 66.0822982788086,
 (55.710339, 37.7275363): 66.09765625,
 (55.7260094, 37.6853501): 66.08338165283203,
 (55.7131667, 37.5433746): 122.74271392822266,
 (55.7738702, 37.6978725): 94.42109680175781,
 (55.9166262, 37.5440168): 66.07589721679688,
 (55.9126493, 37.5444064): 66.0828857421875,
 (55.9356613, 37.5462002): 66.07886505126953,
 (55.9095251, 37.5438905): 66.09038543701172,
 (55.8688828, 37.5467798): 66.11897277832031,
 (55.8109231, 37.5792521): 66.0743179321289,
 (55.8623125, 37.5509694): 66.09358215332031,
 (55.9082771, 37.5434616): 66.09165954589844,
 (55.9094578, 37.5434137): 66.11042785644531,
 (55.9278413, 37.5476208): 66.06306457519531,
 (55.7638612, 37.5572819): 66.09337615966797,
 (55.7648821, 37.5480889): 66.08836364746094,
 (55.769937, 37.5078122): 66.07327270507812,
 (55.7657936, 37.5420796): 66.08797454833984,
 (55.7709755, 37.5014394): 66.0704116821289,
 (55.7664722, 37.5348472): 66.0694580078125,
 (55.7653305, 37.5457429): 66.10154724121094,
 (55.7687916, 37.5174827): 66.11021423339844,
 (55.6510809, 37.6576721): 47.23404312133789,
 (55.6548144, 37.6497538): 47.199710845947266,
 (55.6715782, 37.6277119): 47.191650390625,
 (55.6128958, 37.716612): 47.22187423706055,
 (55.6464914, 37.6695329): 47.19074249267578,
 (55.6359343, 37.6961689): 47.17412185668945,
 (55.6587058, 37.6410313): 47.21610641479492,
 (55.6574989, 37.6436789): 47.19236373901367,
 (55.6396808, 37.6875499): 47.19932174682617,
 (55.630454, 37.7053219): 47.188812255859375}

In [46]:
len(cord_to_value)

57

In [47]:
X = [k for k in cord_to_value.keys()]
Y = [v for v in cord_to_value.values()]

In [48]:
X

[(55.7467696, 37.5727272),
 (55.7458937, 37.5725665),
 (55.752403, 37.5682922),
 (55.7485269, 37.5723747),
 (55.7435597, 37.5384646),
 (55.7667708, 37.5595099),
 (55.7558591, 37.5590651),
 (55.7592331, 37.5580408),
 (55.7700541, 37.5557198),
 (55.7591488, 37.5838317),
 (55.7442717, 37.5718048),
 (55.7355449, 37.5619465),
 (55.7288191, 37.547184),
 (55.7288233, 37.5466866),
 (55.4088783, 37.4747983),
 (55.4153027, 37.4945676),
 (55.4156571, 37.4959933),
 (55.4078659, 37.5512784),
 (55.7080629, 37.74528),
 (55.705214, 37.7669823),
 (55.7093675, 37.731305),
 (55.7094769, 37.7343882),
 (55.7052166, 37.769578),
 (55.7024758, 37.7908443),
 (55.7039351, 37.7796415),
 (55.710339, 37.7275363),
 (55.7260094, 37.6853501),
 (55.7131667, 37.5433746),
 (55.7738702, 37.6978725),
 (55.9166262, 37.5440168),
 (55.9126493, 37.5444064),
 (55.9356613, 37.5462002),
 (55.9095251, 37.5438905),
 (55.8688828, 37.5467798),
 (55.8109231, 37.5792521),
 (55.8623125, 37.5509694),
 (55.9082771, 37.5434616),
 (55.9094578, 37.5434137),
 (55.9278413, 37.5476208),
 (55.7638612, 37.5572819),
 (55.7648821, 37.5480889),
 (55.769937, 37.5078122),
 (55.7657936, 37.5420796),
 (55.7709755, 37.5014394),
 (55.7664722, 37.5348472),
 (55.7653305, 37.5457429),
 (55.7687916, 37.5174827),
 (55.6510809, 37.6576721),
 (55.6548144, 37.6497538),
 (55.6715782, 37.6277119),
 (55.6128958, 37.716612),
 (55.6464914, 37.6695329),
 (55.6359343, 37.6961689),
 (55.6587058, 37.6410313),
 (55.6574989, 37.6436789),
 (55.6396808, 37.6875499),
 (55.630454, 37.7053219)]

In [49]:
Y

[94.3830337524414,
 94.44384765625,
 94.42170715332031,
 94.41339874267578,
 94.42539978027344,
 94.40699768066406,
 94.39757537841797,
 94.40535736083984,
 94.39896392822266,
 94.41742706298828,
 122.71450805664062,
 122.73188018798828,
 122.7625961303711,
 122.7519302368164,
 66.07521057128906,
 66.08165740966797,
 66.09435272216797,
 66.08848571777344,
 66.08900451660156,
 66.05770111083984,
 66.07959747314453,
 66.07525634765625,
 66.07482147216797,
 66.0654296875,
 66.0822982788086,
 66.09765625,
 66.08338165283203,
 122.74271392822266,
 94.42109680175781,
 66.07589721679688,
 66.0828857421875,
 66.07886505126953,
 66.09038543701172,
 66.11897277832031,
 66.0743179321289,
 66.09358215332031,
 66.09165954589844,
 66.11042785644531,
 66.06306457519531,
 66.09337615966797,
 66.08836364746094,
 66.07327270507812,
 66.08797454833984,
 66.0704116821289,
 66.0694580078125,
 66.10154724121094,
 66.11021423339844,
 47.23404312133789,
 47.199710845947266,
 47.191650390625,
 47.22187423706055,
 47.19074249267578,
 47.17412185668945,
 47.21610641479492,
 47.19236373901367,
 47.19932174682617,
 47.188812255859375]

In [69]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
scalar.fit(X)
X_copy = X

X = scalar.transform(X)

In [70]:
model.add(Dense(16, input_dim=2, activation="relu"))

In [71]:
model.add(Dense(8, activation="linear"))

In [72]:
model.add(Dense(4, activation="linear"))

In [73]:
model.add(Dense(1, activation="linear"))

In [74]:
import tensorflow as tf

In [75]:
optimizer = tf.keras.optimizers.RMSprop(0.0099)

In [76]:
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [77]:
model.fit(X,Y,epochs=500)

ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {"<class 'float'>"})

In [59]:
model.predict([(55.7467696, 37.5727272), (55.7288191, 37.547184), (55.6587058, 37.6410313)])

array([[72.11317],
       [72.07961],
       [72.10212]], dtype=float32)

In [ ]:
model.save("./aqi.model")